---

ci:
  skip:
  - stubtest

repos:
- repo: https://github.com/asottile/add-trailing-comma.git
  rev: v2.2.1
  hooks:
  - id: add-trailing-comma

- repo: https://github.com/Lucas-C/pre-commit-hooks.git
  rev: v1.1.12
  hooks:
  - id: remove-tabs

- repo: https://github.com/Lucas-C/pre-commit-hooks-markup.git
  rev: v1.0.1
  hooks:
  - id: rst-linter
    exclude: >-
      (?x)
      CHANGES.rst
      |
      docs/
    files: >-
      ^.*\.rst$

- repo: https://github.com/pre-commit/pre-commit-hooks.git
  rev: v4.1.0
  hooks:
  # Side-effects:
  - id: trailing-whitespace
  - id: check-merge-conflict
  - id: double-quote-string-fixer
  - id: end-of-file-fixer
  # disabled because it doesn't make sense to change pip-tools-managed files
  #- id: requirements-txt-fixer
  #  exclude: >-
  #    (?x)
  #    ^
  #      requirements/[^/]+.txt
  #    $
  #  files: >-
  #    (?x)
  #    ^
  #      requirements/[^/]+.in
  #    $

  # Non-modifying checks:
  - id: name-tests-test
    args:
    - --django
    exclude: cheroot/test/(helper|webtest|_pytest_plugin).py
    files: cheroot/test/.+\.py$
  - id: check-added-large-files
  - id: check-byte-order-marker
  - id: check-case-conflict
  # disabled due to pre-commit/pre-commit-hooks#159
  #- id: check-docstring-first
  - id: check-json
  - id: check-symlinks
  - id: check-yaml
    args:
    - --unsafe
  - id: detect-private-key

  # Heavy checks:
  - id: check-ast
  - id: debug-statements

- repo: https://github.com/PyCQA/pydocstyle.git
  rev: 6.1.1
  hooks:
  - id: pydocstyle

- repo: https://github.com/PyCQA/flake8.git
  rev: 4.0.1
  hooks:
  - id: flake8
    language_version: python3
    additional_dependencies:
    - flake8-2020>=1.6.0
    - flake8-docstrings
    - flake8-pytest-style>=1.0.0
    - wemake-python-styleguide ~= 0.16.0

- repo: https://github.com/Lucas-C/pre-commit-hooks-lxml.git
  rev: v1.1.0
  hooks:
  - id: forbid-html-img-without-alt-text

- repo: https://github.com/pre-commit/mirrors-mypy.git
  rev: v0.931
  hooks:
  - id: mypy
    alias: mypy-py35
    name: MyPy, for Python 3.5
    additional_dependencies:
    - lxml
    - types-backports
    - types-pyOpenSSL
    - types-requests
    - types-six
    args:
    - --install-types
    - --non-interactive
    - --python-version=3.5
    - --txt-report=.tox/.tmp/.mypy/
    - cheroot/
    pass_filenames: false
  - id: mypy
    alias: mypy-py27
    name: MyPy, for Python 2.7
    additional_dependencies:
    - lxml
    - typed-ast
    - types-backports
    - types-pyOpenSSL ~= 21.0  # Last interface supporting Python 2.7
    - types-requests
    - types-six
    - typing
    args:
    - --install-types
    - --non-interactive
    - --python-version=2.7
    - --txt-report=.tox/.tmp/.mypy/
    - cheroot/
    pass_filenames: false

- repo: local
  hooks:
  - id: stubtest
    name: MyPy stubtest
    language: system
    entry: stubtest
    args:
    - cheroot
    - --mypy-config-file=mypy.ini
    - --allowlist=stubtest_allowlist.txt
    pass_filenames: false
    types_or:
    - python
    - text
    files: >-
      (?x)
      ^
        (
          .*\.pyi?
          |
          cheroot/py\.typed
          |
          stubtest_allowlist\.txt
        )
      $

- repo: https://github.com/PyCQA/pylint.git
  rev: v2.12.2
  hooks:
  - id: pylint
    additional_dependencies:
    - jaraco.context
    - jaraco.functools
    - jaraco.text
    - more_itertools
    - portend
    - pylint-pytest < 1.1.0
    - pypytools
    - requests_toolbelt
    - requests_unixsocket
    - six
    - Sphinx
